In [2]:
import pandas as pd

In [3]:
df_fusionné = pd.read_csv('df_fusionné.csv')

In [4]:
df_fusionné_binaire = df_fusionné.sample(frac=0.2)
df_fusionné_binaire.iloc[:, 0] = df_fusionné_binaire.iloc[:, 0].apply(lambda x: 0 if x == 'N' else 1)

In [5]:
# Count the occurrences of each class
counts = df_fusionné_binaire.iloc[:, 0].value_counts()

# Find the number of instances in the minority class
min_count = counts.min()

# Create balanced DataFrame through undersampling
df_balanced_under = pd.concat([
    df_fusionné_binaire[df_fusionné_binaire.iloc[:, 0] == 0].sample(min_count),
    df_fusionné_binaire[df_fusionné_binaire.iloc[:, 0] == 1].sample(min_count)
])

# Shuffle the DataFrame to mix the classes
df_balanced_under = df_balanced_under.sample(frac=1)

In [6]:
# Count occurrences of 0 and 1 in the first column
value_counts = df_balanced_under.iloc[:, 0].value_counts()

# Display the counts
print(value_counts)

ColumnName
0    7502
1    7502
Name: count, dtype: int64

In [7]:
df_balanced_under

,ColumnName,0,1,2,3,4,5,6,7,8,...,710,711,712,713,714,715,716,717,718,719
69987,0,0.447277,0.449700,0.445615,0.448001,0.446976,0.446334,0.448225,0.450906,0.451510,...,0.472199,0.474041,0.473777,0.472685,0.469989,0.467069,0.466257,0.463720,0.469567,0.483022
206193,1,0.516894,0.515376,0.513788,0.511946,0.509812,0.507673,0.505227,0.502938,0.502131,...,0.511320,0.511262,0.511738,0.512462,0.512986,0.513537,0.514550,0.515532,0.516706,0.517642
83510,0,0.506055,0.503119,0.509732,0.500563,0.502451,0.504550,0.499983,0.493772,0.493614,...,0.425448,0.429515,0.426929,0.422203,0.422679,0.425708,0.421414,0.421485,0.427742,0.424281
108652,0,0.481653,0.480629,0.479739,0.478877,0.478708,0.478893,0.479130,0.479554,0.480424,...,0.526195,0.498110,0.486405,0.481755,0.479334,0.479554,0.478833,0.478390,0.479945,0.481992
28793,0,0.508414,0.508213,0.507992,0.507755,0.507549,0.507348,0.507145,0.506943,0.506724,...,0.509317,0.509183,0.509062,0.508956,0.508846,0.508745,0.508688,0.508637,0.508608,0.508568
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92223,0,0.440094,0.439713,0.439293,0.438850,0.438438,0.438023,0.437603,0.437172,0.436673,...,0.442129,0.441929,0.441771,0.441621,0.441450,0.441266,0.441079,0.440871,0.440662,0.440428
8436,1,0.459502,0.459522,0.459548,0.459484,0.459239,0.458980,0.458587,0.458259,0.458624,...,0.452165,0.452716,0.453400,0.454159,0.454849,0.455552,0.456449,0.457350,0.458318,0.459207
178584,0,0.474172,0.474161,0.474143,0.474126,0.474143,0.474172,0.474213,0.474261,0.474283,...,0.474122,0.474069,0.474049,0.474046,0.474045,0.474052,0.474072,0.474096,0.474134,0.474172
204804,1,0.477100,0.476971,0.476911,0.476922,0.476913,0.476919,0.476975,0.477050,0.477099,...,0.483067,0.482218,0.481627,0.481102,0.480625,0.480158,0.479493,0.478803,0.478075,0.477400
143242,0,0.532910,0.535161,0.539473,0.533970,0.535503,0.537050,0.534362,0.530381,0.529089,...,0.487611,0.489628,0.488394,0.486617,0.485093,0.484010,0.487920,0.496710,0.495146,0.484329

In [8]:
import pandas as pd
from sklearn.model_selection import train_test_split


X = df_balanced_under.iloc[:, 1:]  
y = df_balanced_under.iloc[:, 0] 

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [9]:
y_train = y_train.astype(int)
y_test = y_test.astype(int)

In [10]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(12003, 720) (3001, 720) (12003,) (3001,)

In [ ]:
import autokeras as ak

model = ak.StructuredDataClassifier(
    overwrite=True,
    max_trials=3
)

In [ ]:
# Training the model
model.fit(X_train, y_train, validation_split=0.2)

In [ ]:
# evaluate the model
loss, acc = model.evaluate(X_test, y_test, verbose=0)
print('Accuracy: %.3f' % acc)

In [ ]:
# Export the best model
best_model = model.export_model()

# You can now use best_model just like any Keras model
print(best_model.summary())